### PR TITLE
Disable SSL cert verification in ways that are compatible with older

### PR DESCRIPTION
**Pull request by muneeb-ali**
Pythons.

### CODE REVIEW

**Comment by jcnelson** [comment]
This is the branch that fixes ssl handshakes for older versions of python, as well as enables compressed private keys.  It also fixes a bug with sending transactions to chain.com that I discovered while testing.  These changes are not present in master--is it okay if I go ahead and merge them?  Blockstore will not work without these fixes.

**Comment by shea256** [comment]
OK taking a look now.

**Comment by shea256** [comment]
@jcnelson why did you replace:

```python
            if is_int(private_key):
                secret_exponent = private_key
            elif is_256bit_hex_string(private_key):
                secret_exponent = int(private_key, 16)
            elif is_wif_pk(private_key):
                secret_exponent = int(
                    hexlify(b58check_decode(private_key)), 16)
            else:
                raise Exception('Not a valid private key format.')
```

with

```python
private_key = encode_privkey( private_key, 'decimal' )
secret_exponent = private_key
```

It seems this breaks things and removes the ability to pass in private key strings of any format.

**Comment by shea256** [comment]
Also, in this file you're assuming that the desired format is compressed: https://github.com/blockstack/pybitcoin/blob/ssl_noverify_oldpython/pybitcoin/transactions/network.py

Any particular reason why? Both compressed and uncompressed keys need to be supported.

**Comment by jcnelson** [comment]
@shea256 The encode_privkey() method from pybitcointools [1] takes a private key encoded in one of the formats it supports (i.e. decimal, bin, bin_compressed, hex, hex_compressed, wif, wif_compressed) and outputs the same private key in the requested format.  Maybe I've misread the code, but it seems that the purpose of the BitcoinPrivateKey constructor is to take an encoded private key (in one of the above formats) and extract its secret exponent as a decimal.  The encode_privkey() method, as used in this pull request, does exactly that.

The sign_transaction method (imported from pybitcointools.sign) will decode the given key regardless of whether or not it is compressed; the "compressed=True" flag proves unnecessary and can be removed from network.py.  However, it has been my experience that the UTXO provider (chain.com in my case) does not seem to recognize uncompressed addresses.  This is part of what necessitated this patch--I need to ensure that the address we feed into the request is compressed.

[1] https://github.com/vbuterin/pybitcointools/blob/master/bitcoin/main.py

**Comment by shea256** [comment]
Here is the encode_privkey() code:

```python
def encode_privkey(priv, formt, vbyte=0):
    if not isinstance(priv, int_types):
        return encode_privkey(decode_privkey(priv), formt, vbyte)
    if formt == 'decimal': return priv
    elif formt == 'bin': return encode(priv, 256, 32)
    elif formt == 'bin_compressed': return encode(priv, 256, 32)+b'\x01'
    elif formt == 'hex': return encode(priv, 16, 64)
    elif formt == 'hex_compressed': return encode(priv, 16, 64)+'01'
    elif formt == 'wif':
        return bin_to_b58check(encode(priv, 256, 32), 128+int(vbyte))
    elif formt == 'wif_compressed':
        return bin_to_b58check(encode(priv, 256, 32)+b'\x01', 128+int(vbyte))
    else: raise Exception("Invalid format!")
```

If you provide "decimal" as the format, it assumes the private key was already in decimal format and just returns the input.

**Comment by jcnelson** [comment]
@shea256 If the private key is not an integer already, then the line
```
    return encode_privkey(decode_privkey(priv), formt, vbyte)
```
is executed, as desired.

**Comment by shea256** [comment]
OK the decode_privkey function is a little strange. Nonetheless, our goal should be to not rely on pybitcointools at all. I have included some functions in there as temporary hacks.

**Comment by shea256** [comment]
I'd keep the existing code that I have in privatekey.py, since it's much easier to understand, doesn't rely on pybitcointools, and provides proper error reporting.

**Comment by shea256** [comment]
@jcnelson both compressed and uncompressed addresses are supported. It just so happens that more and more wallets are switching to compressed keys so you may see a lot of keys. Please note that for a given compressed private key, only the compressed public key and equivalent address based on the compressed public key will be supported (and the same is true for the uncompressed private key).

In fact, onename.com only uses uncompressed keys right now. In general, supporting uncompressed keys is strictly required.

**Comment by jcnelson** [comment]
I just pushed some additional code that addresses the issues we discussed in person:
* we detect whether or not a public key or private key is compressed.
* we do not allow the client to choose whether or not they want the key in compressed or uncompressed format (since this is just asking for trouble, given the construction of Bitcoin private keys).
* the code no longer uses the compressed= keyword argument.

**Comment by shea256** [comment]
Woot! I'm just going to pull and run the tests.

**Comment by shea256** [comment]
Merged! :dancers:

**Pull request merged**
